config/routes.rb
Rails.application.routes.draw do
  root to: 'page#index'  

  
   match '/questime',       to: 'questime#index',       via: 'get'
  
  
   match '/info',       to: 'page#info',       via: 'get'
   match '/contact',    to: 'page#contact',    via: 'get'
   
   match '/blog',       to: 'page#blog',    	via: 'get'
   match '/blog1',       to: 'page#blog1',    	via: 'get'
   match '/blog2',       to: 'page#blog2',    	via: 'get'
   match '/blog3',       to: 'page#blog3',    	via: 'get'
   
   match '/mafia',      to: 'mafia#mafia', 	via: 'get'
 
   match '/quest',      to: 'quest#quest',  	via: 'get'
   match '/quest1',      to: 'quest#quest1',  	via: 'get'
   match '/quest2',      to: 'quest#quest2',  	via: 'get'
   match '/quest3',      to: 'quest#quest3',  	via: 'get'
 
   match '/deti',       to: 'deti#deti',   	via: 'get'
   match '/deti1',       to: 'deti#deti1',   	via: 'get'
   match '/deti2',       to: 'deti#deti2',   	via: 'get'
   match '/deti3',       to: 'deti#deti3',   	via: 'get'
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/css_controller.rb
class CssController < ApplicationController

  def show
  end

end

app/controllers/deti_controller.rb
class DetiController < ApplicationController
  def deti
  end
end

app/controllers/mafia_controller.rb
class MafiaController < ApplicationController

  def mafia
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController

  def contact
  end
  
  def deti
  end
  
  def info
  end
  
  def mafia
  end
  
  def quest
  end
  
end

app/controllers/quest_controller.rb
class QuestController < ApplicationController

  def quest
  end

end

app/controllers/questime_controller.rb
class QuestimeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/css_helper.rb
module CssHelper
end

app/helpers/deti_helper.rb
module DetiHelper
end

app/helpers/mafia_helper.rb
module MafiaHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/quest_helper.rb
module QuestHelper
end

app/helpers/questime_helper.rb
module QuestimeHelper
end

app/views/deti/deti1.html.erb
<%= render 'layouts/header' %>
<div class="content">

   <h1>дети Квесты</h1>

 <h1>Супергерои</h1>


	

	Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться. Lorem Ipsum используют потому, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации "Здесь ваш текст.. Здесь ваш текст.. Здесь ваш текст.." Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию, так что поиск по ключевым словам "lorem ipsum" сразу показывает, как много веб-страниц всё ещё дожидаются своего настоящего рождения. За прошедшие годы текст Lorem Ipsum получил много версий. Некоторые версии появились по ошибке, некоторые - намеренно (например, юмористические варианты).
	Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться. Lorem Ipsum используют потому, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации "Здесь ваш текст.. Здесь ваш текст.. Здесь ваш текст.." Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию, так что поиск по ключевым словам "lorem ipsum" сразу показывает, как много веб-страниц всё ещё дожидаются своего настоящего рождения. За прошедшие годы текст Lorem Ipsum получил много версий. Некоторые версии появились по ошибке, некоторые - намеренно (например, юмористические варианты).
	Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться. Lorem Ipsum используют потому, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации "Здесь ваш текст.. Здесь ваш текст.. Здесь ваш текст.." Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию, так что поиск по ключевым словам "lorem ipsum" сразу показывает, как много веб-страниц всё ещё дожидаются своего настоящего рождения. За прошедшие годы текст Lorem Ipsum получил много версий. Некоторые версии появились по ошибке, некоторые - намеренно (например, юмористические варианты).
	Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться. Lorem Ipsum используют потому, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации "Здесь ваш текст.. Здесь ваш текст.. Здесь ваш текст.." Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию, так что поиск по ключевым словам "lorem ipsum" сразу показывает, как много веб-страниц всё ещё дожидаются своего настоящего рождения. За прошедшие годы текст Lorem Ipsum получил много версий. Некоторые версии появились по ошибке, некоторые - намеренно (например, юмористические варианты).
	Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться. Lorem Ipsum используют потому, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации "Здесь ваш текст.. Здесь ваш текст.. Здесь ваш текст.." Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию, так что поиск по ключевым словам "lorem ipsum" сразу показывает, как много веб-страниц всё ещё дожидаются своего настоящего рождения. За прошедшие годы текст Lorem Ipsum получил много версий. Некоторые версии появились по ошибке, некоторые - намеренно (например, юмористические варианты).

		<p class="linkAp"> <a href="#"> НАВЕРХ </a> </p>
		<p class="linkAp"><%= link_to "Назад", deti_path %></p>
</div>

app/views/deti/deti2.html.erb
<%= render 'layouts/header' %>
<div class="content">

   <h1>дети Квесты</h1>

 <h1>Рыцари</h1>


	

	Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться. Lorem Ipsum используют потому, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации "Здесь ваш текст.. Здесь ваш текст.. Здесь ваш текст.." Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию, так что поиск по ключевым словам "lorem ipsum" сразу показывает, как много веб-страниц всё ещё дожидаются своего настоящего рождения. За прошедшие годы текст Lorem Ipsum получил много версий. Некоторые версии появились по ошибке, некоторые - намеренно (например, юмористические варианты).
	Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться. Lorem Ipsum используют потому, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации "Здесь ваш текст.. Здесь ваш текст.. Здесь ваш текст.." Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию, так что поиск по ключевым словам "lorem ipsum" сразу показывает, как много веб-страниц всё ещё дожидаются своего настоящего рождения. За прошедшие годы текст Lorem Ipsum получил много версий. Некоторые версии появились по ошибке, некоторые - намеренно (например, юмористические варианты).
	Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться. Lorem Ipsum используют потому, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации "Здесь ваш текст.. Здесь ваш текст.. Здесь ваш текст.." Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию, так что поиск по ключевым словам "lorem ipsum" сразу показывает, как много веб-страниц всё ещё дожидаются своего настоящего рождения. За прошедшие годы текст Lorem Ipsum получил много версий. Некоторые версии появились по ошибке, некоторые - намеренно (например, юмористические варианты).
	Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться. Lorem Ipsum используют потому, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации "Здесь ваш текст.. Здесь ваш текст.. Здесь ваш текст.." Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию, так что поиск по ключевым словам "lorem ipsum" сразу показывает, как много веб-страниц всё ещё дожидаются своего настоящего рождения. За прошедшие годы текст Lorem Ipsum получил много версий. Некоторые версии появились по ошибке, некоторые - намеренно (например, юмористические варианты).
	Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться. Lorem Ipsum используют потому, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации "Здесь ваш текст.. Здесь ваш текст.. Здесь ваш текст.." Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию, так что поиск по ключевым словам "lorem ipsum" сразу показывает, как много веб-страниц всё ещё дожидаются своего настоящего рождения. За прошедшие годы текст Lorem Ipsum получил много версий. Некоторые версии появились по ошибке, некоторые - намеренно (например, юмористические варианты).

		<p class="linkAp"> <a href="#"> НАВЕРХ </a> </p>
		<p class="linkAp"><%= link_to "Назад", quest_path %></p>
</div>

app/views/deti/deti3.html.erb
<%= render 'layouts/header' %>
<div class="content">

   <h1>дети Квесты</h1>

 <h1>Не знаю</h1>


	

	Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться. Lorem Ipsum используют потому, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации "Здесь ваш текст.. Здесь ваш текст.. Здесь ваш текст.." Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию, так что поиск по ключевым словам "lorem ipsum" сразу показывает, как много веб-страниц всё ещё дожидаются своего настоящего рождения. За прошедшие годы текст Lorem Ipsum получил много версий. Некоторые версии появились по ошибке, некоторые - намеренно (например, юмористические варианты).
	Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться. Lorem Ipsum используют потому, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации "Здесь ваш текст.. Здесь ваш текст.. Здесь ваш текст.." Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию, так что поиск по ключевым словам "lorem ipsum" сразу показывает, как много веб-страниц всё ещё дожидаются своего настоящего рождения. За прошедшие годы текст Lorem Ipsum получил много версий. Некоторые версии появились по ошибке, некоторые - намеренно (например, юмористические варианты).
	Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться. Lorem Ipsum используют потому, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации "Здесь ваш текст.. Здесь ваш текст.. Здесь ваш текст.." Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию, так что поиск по ключевым словам "lorem ipsum" сразу показывает, как много веб-страниц всё ещё дожидаются своего настоящего рождения. За прошедшие годы текст Lorem Ipsum получил много версий. Некоторые версии появились по ошибке, некоторые - намеренно (например, юмористические варианты).
	Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться. Lorem Ipsum используют потому, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации "Здесь ваш текст.. Здесь ваш текст.. Здесь ваш текст.." Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию, так что поиск по ключевым словам "lorem ipsum" сразу показывает, как много веб-страниц всё ещё дожидаются своего настоящего рождения. За прошедшие годы текст Lorem Ipsum получил много версий. Некоторые версии появились по ошибке, некоторые - намеренно (например, юмористические варианты).
	Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться. Lorem Ipsum используют потому, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации "Здесь ваш текст.. Здесь ваш текст.. Здесь ваш текст.." Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию, так что поиск по ключевым словам "lorem ipsum" сразу показывает, как много веб-страниц всё ещё дожидаются своего настоящего рождения. За прошедшие годы текст Lorem Ipsum получил много версий. Некоторые версии появились по ошибке, некоторые - намеренно (например, юмористические варианты).

		<p class="linkAp"> <a href="#"> НАВЕРХ </a> </p>
		<p class="linkAp"><%= link_to "Назад", deti_path %></p>
</div>

app/views/layouts/XL/_menuBlog.html.erb
	<div id="leftside">
		<h1>Живые квесты</h1>
		<h2>Наше Развитие</h2>

		<div id="menu">
			<a><%= link_to "Главная", 			root_path%>
			<%= link_to "Статьи", 					blog_path, class: "active"  %>
			<%= link_to "Взрослые квесты", 	quest_path %>
			<%= link_to "Детские квесты", 	deti_path %>
			<%= link_to "Мафия", 						mafia_path %>
			<%= link_to "О Нас", 						info_path %>
			<%= link_to "Контакты", 				contact_path%></a>		
		</div>

		<h3>Здесь находятся</h3>
		<p>Контакты</p>
	
	</div>
</div>

app/views/layouts/XL/_menuContact.html.erb
	<div id="leftside">
		<h1>Живые квесты</h1>
		<h2>Наша Польза</h2>

		<div id="menu">
			<a><%= link_to "Главная", 			root_path%>
			<%= link_to "Статьи", 					blog_path %>
			<%= link_to "Взрослые квесты", 	quest_path %>
			<%= link_to "Детские квесты", 	deti_path %>
			<%= link_to "Мафия", 						mafia_path %>
			<%= link_to "О Нас", 						info_path %>
			<%= link_to "Контакты", 				contact_path, class: "active" %></a>		
		</div>
	
		<h3>Здесь находятся</h3>
		<p>Контакты</p>
	
	</div>
</div>

app/views/layouts/XL/_menuDeti.html.erb
  <div id="leftside">
    <h1>Дети </h1>
    <h2>Наше все</h2>

<div id="menu">
      <a><%= link_to "Главная",       root_path%>
      <%= link_to "Статьи",           blog_path%>
      <%= link_to "Взрослые квесты",  quest_path %>
      <%= link_to "Детские квесты",   deti_path, class: "active"    %>
      <%= link_to "Мафия",            mafia_path %>
      <%= link_to "О Нас",            info_path%>
      <%= link_to "Контакты",         contact_path%></a>    
    </div>

    <h3>Здесь находятся</h3>
    <p>Контакты</p>
  
  </div>
</div>

app/views/layouts/XL/_menuIndex.html.erb
	<div id="leftside">
		<h1>Живые квесты</h1>
		<h2>Наша жизнь</h2>
		
		<div id="menu">
			<a><%= link_to "Главная", 			root_path, class: "active"%>
			<%= link_to "Статьи", 					blog_path %>
			<%= link_to "Взрослые квесты", 	quest_path %>
			<%= link_to "Детские квесты", 	deti_path %>
			<%= link_to "Мафия", 						mafia_path %>
			<%= link_to "О Нас", 						info_path %>
			<%= link_to "Контакты", 				contact_path %></a>
		</div>
	
		<h3>Здесь находятся</h3>
		<p>Контакты</p>
	
	</div>
</div>

app/views/layouts/XL/_menuInfo.html.erb
	<div id="leftside">
		<h1>Живые квесты</h1>
		<h2>Наше Призвание</h2>

		<div id="menu">
			<a><%= link_to "Главная", 			root_path%>
			<%= link_to "Статьи", 					blog_path%>
			<%= link_to "Взрослые квесты", 	quest_path %>
			<%= link_to "Детские квесты", 	deti_path %>
			<%= link_to "Мафия", 						mafia_path %>
			<%= link_to "О Нас", 						info_path, class: "active"   %>
			<%= link_to "Контакты", 				contact_path%></a>		
		</div>

	
		<h3>Здесь находятся</h3>
		<p>Контакты</p>
	
	</div>
</div>

app/views/layouts/XL/_menuMafia.html.erb
	<div id="leftside">
		<h1>Живые квесты</h1>
		<h2>Наше Преимущество</h2>

<div id="menu">
      <a><%= link_to "Главная",       root_path%>
      <%= link_to "Статьи",           blog_path%>
      <%= link_to "Взрослые квесты",  quest_path %>
      <%= link_to "Детские квесты",   deti_path%>
      <%= link_to "Мафия",            mafia_path, class: "active"     %>
      <%= link_to "О Нас",            info_path%>
      <%= link_to "Контакты",         contact_path%></a>    
    </div>

		<h3>Здесь находятся</h3>
		<p>Контакты</p>
	
	</div>
</div>

app/views/layouts/XL/_menuQuest.html.erb
  <div id="leftside">
    <h1>Живые квесты</h1>
    <h2>Наше Творчество</h2>

<div id="menu">
      <a><%= link_to "Главная",       root_path%>
      <%= link_to "Статьи",           blog_path%>
      <%= link_to "Взрослые квесты",  quest_path, class: "active"      %>
      <%= link_to "Детские квесты",   deti_path%>
      <%= link_to "Мафия",            mafia_path%>
      <%= link_to "О Нас",            info_path%>
      <%= link_to "Контакты",         contact_path%></a>    
    </div>

    <h3>Здесь находятся</h3>
    <p>Контакты</p>
  
  </div>
</div>

app/views/layouts/XL/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/XL/_sidebar.html.erb
<footer>
    <ul class="f-fobar">
      <li class="f-menu"><%= link_to "что",   "#"  %></li>
      <li class="f-menu"><%= link_to "Же","#" %></li>
      <li class="f-menu"><%= link_to "Сюда",   "#"  %></li>
      <li class="f-menu"><%= link_to "Написать??","#" %></li>
     </ul>
</footer>

app/views/layouts/_footer.html.erb
<footer>
    здесь ссылка на группу ВК
</footer>

app/views/layouts/_header.html.erb
<header>
	<div class="row">

		<div class="logo">ЛОГОТИП</div>
		<div class="contact">КОНТАКТЫ</div>

<ul id="menu">
    <li><%= link_to "Главная", root_path %></li>
    <li><%= link_to "Статьи", blog_path %>
        <ul>
            <li><%= link_to "Статья 1", blog1_path %></li>
            <li><%= link_to "Статья 2", blog2_path %></li>
            <li><%= link_to "Статья 3", blog3_path %></li>
            
        </ul>
    </li>
    <li><%= link_to "Для взрослых", 	quest_path %>
        <ul>
            <li><%= link_to "Дирижабль", quest1_path %></li>
            <li><%= link_to "Детектив", quest2_path %></li>
            <li><%= link_to "Мафия", quest3_path %></li>
        </ul>
    </li>       
     <li><%= link_to "Для Детей", 	deti_path %>
        <ul>
            <li><%= link_to "Супергерои", deti1_path %></li>
            <li><%= link_to "Рыцари", deti2_path %></li>
            <li><%= link_to "Не знаю", deti3_path %></li>
        </ul>
    </li>    
    
    <li><%= link_to "Мафия", mafia_path %></li>
    <li><%= link_to "Контакты", contact_path %></li>
    <li><%= link_to "О Нас", info_path %></li>
   
</ul>
<hr>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= 123  %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    </head>
      <body>
  	
      <%= yield %>
      
      </body>
</html>

app/views/page/blog.html.erb
<%= render 'layouts/header' %>
	
<div class="content">
	
		<h1>Здесь будет полезная информация по живым квестам?</h1>

		<h3>Список статей:</h3>
		
		<p>Что такое живые квесты?</p>
		<p>Какие они бывают?</p>
		<p>Какая польза?</p>	

			<li><%= link_to "Статья 1", blog1_path %></li>
            <li><%= link_to "Статья 2", blog2_path %></li>
            <li><%= link_to "Статья 3", blog3_path %></li>
            


	Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться. Lorem Ipsum используют потому, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации "Здесь ваш текст.. Здесь ваш текст.. Здесь ваш текст.." Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию, так что поиск по ключевым словам "lorem ipsum" сразу показывает, как много веб-страниц всё ещё дожидаются своего настоящего рождения. За прошедшие годы текст Lorem Ipsum получил много версий. Некоторые версии появились по ошибке, некоторые - намеренно (например, юмористические варианты).
	Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться. Lorem Ipsum используют потому, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации "Здесь ваш текст.. Здесь ваш текст.. Здесь ваш текст.." Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию, так что поиск по ключевым словам "lorem ipsum" сразу показывает, как много веб-страниц всё ещё дожидаются своего настоящего рождения. За прошедшие годы текст Lorem Ipsum получил много версий. Некоторые версии появились по ошибке, некоторые - намеренно (например, юмористические варианты).
	Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться. Lorem Ipsum используют потому, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации "Здесь ваш текст.. Здесь ваш текст.. Здесь ваш текст.." Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию, так что поиск по ключевым словам "lorem ipsum" сразу показывает, как много веб-страниц всё ещё дожидаются своего настоящего рождения. За прошедшие годы текст Lorem Ipsum получил много версий. Некоторые версии появились по ошибке, некоторые - намеренно (например, юмористические варианты).
	Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться. Lorem Ipsum используют потому, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации "Здесь ваш текст.. Здесь ваш текст.. Здесь ваш текст.." Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию, так что поиск по ключевым словам "lorem ipsum" сразу показывает, как много веб-страниц всё ещё дожидаются своего настоящего рождения. За прошедшие годы текст Lorem Ipsum получил много версий. Некоторые версии появились по ошибке, некоторые - намеренно (например, юмористические варианты).
	Давно выяснено, что при оценке дизайна и композиции читаемый текст мешает сосредоточиться. Lorem Ipsum используют потому, что тот обеспечивает более или менее стандартное заполнение шаблона, а также реальное распределение букв и пробелов в абзацах, которое не получается при простой дубликации "Здесь ваш текст.. Здесь ваш текст.. Здесь ваш текст.." Многие программы электронной вёрстки и редакторы HTML используют Lorem Ipsum в качестве текста по умолчанию, так что поиск по ключевым словам "lorem ipsum" сразу показывает, как много веб-страниц всё ещё дожидаются своего настоящего рождения. За прошедшие годы текст Lorem Ipsum получил много версий. Некоторые версии появились по ошибке, некоторые - намеренно (например, юмористические варианты).

		<p class="linkAp"> <a href="#"> НАВЕРХ </a> </p>
		<p class="linkAp"><%= link_to "Назад", blog_path %></p>

</div>

<%= render 'layouts/footer' %>




		